# Generated by Django 4.1 on 2022-08-27 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Color',
        ),
    ]
