# Generated by Django 4.1 on 2022-08-27 17:29

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category', models.CharField(blank=True, choices=[('1', 'Man'), ('2', 'Woman'), ('3', 'Kids')], max_length=255, null=True)),
                ('sku', models.CharField(blank=True, max_length=355, unique=True)),
                ('product_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField()),
                ('product_totel_stoke', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('product_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reference_brand', to='category.brand')),
                ('product_sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_reference_sub_category', to='category.subcategory')),
            ],
            options={
                'verbose_name_plural': 'Product',
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='SubProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_product_totel_stoke', models.IntegerField(blank=True, null=True)),
                ('offerprice', models.DecimalField(decimal_places=2, max_digits=6)),
                ('offer_persentage', models.CharField(blank=True, max_length=255, null=True)),
                ('offer_expiry_date', models.DateTimeField()),
                ('offer_stoke', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_product_reference_main_product', to='products.product')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_product_reference_size', to='category.size')),
            ],
            options={
                'verbose_name_plural': 'sub Product Attribute',
            },
        ),
        migrations.CreateModel(
            name='SubProductAttributeImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('images', models.ImageField(blank=True, null=True, upload_to=products.models.upload_image_path)),
                ('product_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_product_images_reference_sub_product', to='products.subproductattribute')),
            ],
            options={
                'verbose_name_plural': 'sub product attribute image',
            },
        ),
        migrations.CreateModel(
            name='ProductQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product_Quantity_referece_offer_product', to='products.subproductattribute')),
            ],
            options={
                'verbose_name_plural': 'Product Quantity',
            },
        ),
    ]
