# Generated by Django 4.1 on 2022-08-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('products', '0002_subproductattribute_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subproductattribute',
            name='size',
        ),
        migrations.AddField(
            model_name='subproductattribute',
            name='size',
            field=models.ManyToManyField(blank=True, null=True, related_name='sub_product_reference_size', to='category.size'),
        ),
    ]
